name = "nomio-gateway"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
# 不配置 routes，使用 Worker 路由规则手动配置
# 这样可以排除 dash 和 api 子域名

[[d1_databases]]
binding = "DB"
database_name = "nomio-prod-db"
database_id = "540a34d9-5d96-4bbf-8e44-00127652f032"
