name = "nomio-gateway"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "*.nomio.world/*", zone_name = "nomio.world" }
]

[[d1_databases]]
binding = "DB"
database_name = "nomio-prod-db"
database_id = "540a34d9-5d96-4bbf-8e44-00127652f032"
