name = "nomio-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "nomio-db"
database_id = "f0616555-1157-4062-b9ef-f27d56831d02"

[vars]
JWT_SECRET = "8d584ef0ba266b97d22be95fe97684003353e6b39f8373f33e9b0488afcd28f8"
ALLOWED_ORIGINS = "*"
